apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tuto
  name: tuto
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tuto
  template:
    metadata:
      labels:
        app: tuto
    spec:
      containers:
      - image: allayayahya/tuto:latest
        name: tuto
        ports:
        - containerPort: 5000